//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public DONHANG()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public int MaDH { get; set; }
        public int MaND { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TrangThai { get; set; }
        public string PhuongThucThanhToan { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual ICollection<VE> VEs { get; set; }
    }
}
