//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHE
    {
        public GHE()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.VEs = new HashSet<VE>();
        }
    
        public int MaGhe { get; set; }
        public int MaPhong { get; set; }
        public string DayGhe { get; set; }
        public Nullable<int> SoGhe { get; set; }
        public string LoaiGhe { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual ICollection<VE> VEs { get; set; }
    }
}
