//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        public PHIM()
        {
            this.SUATCHIEUx = new HashSet<SUATCHIEU>();
        }
    
        public int MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string MoTa { get; set; }
        public int ThoiLuong { get; set; }
        public string TheLoai { get; set; }
        public Nullable<System.DateTime> NgayKhoiChieu { get; set; }
        public string Poster { get; set; }
        public string QuocGia { get; set; }
        public string Trailer { get; set; }
    
        public virtual ICollection<SUATCHIEU> SUATCHIEUx { get; set; }
    }
}
