//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public PHONG()
        {
            this.GHEs = new HashSet<GHE>();
            this.SUATCHIEUx = new HashSet<SUATCHIEU>();
        }
    
        public int MaPhong { get; set; }
        public int MaRap { get; set; }
        public string TenPhong { get; set; }
        public int SoLuongGhe { get; set; }
    
        public virtual ICollection<GHE> GHEs { get; set; }
        public virtual RAP RAP { get; set; }
        public virtual ICollection<SUATCHIEU> SUATCHIEUx { get; set; }
    }
}
