//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatVe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_DatVeXemPhimEntities1 : DbContext
    {
        public QL_DatVeXemPhimEntities1()
            : base("name=QL_DatVeXemPhimEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DONHANG> DONHANGs { get; set; }
        public DbSet<GHE> GHEs { get; set; }
        public DbSet<GIOHANG> GIOHANGs { get; set; }
        public DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public DbSet<PHIM> PHIMs { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
        public DbSet<RAP> RAPs { get; set; }
        public DbSet<SUATCHIEU> SUATCHIEUx { get; set; }
        public DbSet<VE> VEs { get; set; }
    }
}
