//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAP
    {
        public RAP()
        {
            this.PHONGs = new HashSet<PHONG>();
        }
    
        public int MaRap { get; set; }
        public string TenRap { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
