//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public int MaVe { get; set; }
        public int MaDH { get; set; }
        public int MaSuat { get; set; }
        public int MaGhe { get; set; }
        public decimal Gia { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual GHE GHE { get; set; }
        public virtual SUATCHIEU SUATCHIEU { get; set; }
    }
}
